### ISSUE TITLE
Problema de segurança - vazamento de private key do serviço de deploy 

### ISSUE THREAD

**Issue by MedeirosJoel** [MateusOF5512/UFSC_em_dados#1]
Olá boa tarde! Primeiramente parabéns pelo projeto muito interessante.
Gostaria de alertá-lo que private keys devem ficar nas variáveis de ambiente e não escritas no código, uma pessoa mal intecionada poderia tranquilamente usar.

Recomendo que apague o arquivo: `dados/streamlit-373718-f2e709f0d5bc.json` até que você aprenda a utilizar variáveis de ambiente no seu projeto.

**Comment by MateusOF5512** [comment]
Boa tarde, agradeço o feedback e o alerta sobre a private key, publiquei desta forma para ver se rodava e não fui atrás de estudar de como armazenar as variáveis de ambiente, vou fazer isso agora, muito obrigado
